name: cafetaria
description: Komplekku cafetaria

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  cafetaria_ui:
    path: packages/cafetaria_ui
  category_repository:
    path: packages/category_repository
  cloud_firestore: ^3.2.1
  cloud_storage:
    path: packages/cloud_storage
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_messaging: ^11.4.4
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.2
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  menu_repository:
    path: packages/menu_repository
  shared_preferences: ^2.0.15
  storage:
    path: packages/storage
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
  # colors:
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
