name: rating_repository
description: rating repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  flutter:
    sdk: flutter
  uuid: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0