name: cloud_storage
description: Cloud Storage Service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.3
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.0
