name: category_repository
description: A new Flutter package project.
version: 0.0.1
homepage: nahrub wakhid

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.2.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.6.0
  uuid: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.0





flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
