name: cafetaria

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - ".github/workflows/main.yaml"
      - "pubspec.yaml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 3.0.2
          channel: "stable"

      - name: Install Dependencies
        run: flutter packages get
        
      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      # - name: Verify
      #   run: flutter test -t presubmit-only

      - name: Run tests
        run: flutter test -x presubmit-only --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          exclude: "**/*.g.dart **/*.gen.dart **/main/bootstrap.dart"
          min_coverage: 0
          path: coverage/lcov.info